# Generated by Django 5.2 on 2025-05-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_bid_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imageURL',
            field=models.CharField(default='none'),
        ),
    ]
