# Generated by Django 5.2 on 2025-06-01 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_watchlisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchlisted',
        ),
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
